
services:
#  app:
#    image: ghcr.io/cdtester/docker-example:latest
  playwright:
    build:
      context: ./playwright
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    volumes:
      - ./playwright/allure-results:/app/allure-results
      - ./playwright/allure-report:/app/allure-report
    environment:
      - TEST_ARGS=--grep @smoke
      - CI=true

